### ISSUE TITLE
Support of PHP 7.4

### ISSUE THREAD

**Issue by xmav** [tomzx/php-semver-checker#106]
Hi!

I am wonder if you have plan to add support of PHP 7.3 and up to your tool?
For now it is limited to PHP 7.2 by "nikic/php-parser": "^3.1" which seems to be unsupported version.

Thanks,
Maksym

**Comment by tomzx** [comment]
Fixed @ 9f7f98ed554b8201d95756b2a0b7f3da9118358c.

**Comment by xmav** [comment]
Great! Are you going to release new version with those changes ? When can I expect it to be released ?

**Comment by tomzx** [comment]
https://github.com/tomzx/php-semver-checker/releases/tag/v0.14.0

**Comment by xmav** [comment]
Fantastic!
