### ISSUE TITLE
Readme Example Not Very Fair

### ISSUE THREAD

**Issue by GrahamCampbell** [tomzx/php-semver-checker#11]
Laravel 4.2.15->4.2.16 was a bc break because it was restoring the code to how it was at an earlier 4.2 release to actually stop the bc break.

**Comment by tomzx** [comment]
Fair enough.

Do you have any suggested tags to compare, library to test on or another output the README could contain?

**Comment by GrahamCampbell** [comment]
Perhaps test it on one of the phpleague projects. https://github.com/thephpleague/factory-muffin.

I'd actually be interested to see what this tool says about my versioning. :)

**Comment by tomzx** [comment]
You may want to use [php-semver-checker-git](https://github.com/tomzx/php-semver-checker-git), a little tool I wrote just after the initial development of this library. It allows you to run the check against a git repository which makes it a bit easier to use than having to create two copies of the source.

Any specific tags to run against factory-muffin?

**Comment by GrahamCampbell** [comment]
Any of the 2.x tags should be good. We're following semver from 2.0.0. :)

**Comment by GrahamCampbell** [comment]
Maybe comparing v1.6.4 with v2.0.0 would give you a bit output to show off the tool. :)

**Comment by tomzx** [comment]
``` bash
Suggested semantic versioning change: MAJOR

CLASS
LEVEL LOCATION  REASON
MAJOR src/Zizaco/FactoryMuff/Facade/FactoryMuff.php#8 Zizaco\FactoryMuff\Facade\FactoryMuff Class was removed.
MAJOR src/Zizaco/FactoryMuff/FactoryMuff.php#13 Zizaco\FactoryMuff\FactoryMuff  Class was removed.
MAJOR src/Zizaco/FactoryMuff/Kind.php#7 Zizaco\FactoryMuff\Kind Class was removed.
[...]
MINOR src/Exceptions/DeleteFailedException.php#17 League\FactoryMuffin\Exceptions\DeleteFailedException Class was added.
MINOR src/Exceptions/DeleteMethodNotFoundException.php#17 League\FactoryMuffin\Exceptions\DeleteMethodNotFoundException Class was added.
MINOR src/Exceptions/DeletingFailedException.php#21 League\FactoryMuffin\Exceptions\DeletingFailedException Class was added.
[... cut for brievity ...]

FUNCTION
LEVEL LOCATION  REASON
```

Looks good to you?

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by tomzx** [comment]
Updated @ 019f099a482ee05da0a7ef2c24cef8760ec46e81.

Let me know if there's any issue.
