### ISSUE TITLE
Separate the target (what) from the location (where)

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker#14]
Currently

`src/Zizaco/FactoryMuff/Facade/FactoryMuff.php#8 Zizaco\FactoryMuff\Facade\FactoryMuff`

displays in the `Location` column. It would make more sense if

`src/Zizaco/FactoryMuff/Facade/FactoryMuff.php#8` was in the `Location` column

`Zizaco\FactoryMuff\Facade\FactoryMuff` was in a new `Target` column

**Comment by xabbuh** [comment]
@tomzx Would be good to update the example in the readme accordingly.
