### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by coldwinds** [tomzx/php-semver-checker#15]
Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tomzx/php-semver-checker dev-master -> satisfiabl
e by tomzx/php-semver-checker[dev-master].
    - tomzx/php-semver-checker dev-master requires symfony/console 2.7.*@dev ->
no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by tomzx** [comment]
Hi,

To install in its current state, you need the following composer.json:

``` json
{
    "name": "tomzx/php-semver-checker-test",
    "require": {
        "tomzx/php-semver-checker": "0.1.x@dev",
        "symfony/console": "2.7.*@dev"
    }
}

```

**Comment by coldwinds** [comment]
Works fine, thanks tomzx.

**Comment by tomzx** [comment]
Let me know if you have any other issue.
