### ISSUE TITLE
Please provide a PHAR

### ISSUE THREAD

**Issue by ScreamingDev** [tomzx/php-semver-checker#18]
This tool is nice but it breaks projects which depend on stable releases.

I have some requirements in the composer.json. To add php-semver-checker I need to enable the minimum-stability of "dev" versions. When composer installs it fetches dev-versions of all requirements.

This breaks the application and dev can never be trusted or rolled out for end-users.

So please provide a downloadable PHAR-File containing your tool. Many people like to use it as I see.

**Comment by ArnaudLigny** [comment]
:+1:

**Comment by mikeSimonson** [comment]
You can also just install it globally.
Which make sense as it is a tool to work on any of your project.
It doesn't add a feature to yours.

``` sh
$ composer global require tomzx/php-semver-checker
```

**Comment by tomzx** [comment]
The current issue with building a phar is deploying/hosting it. For the moment it is simpler for me to have people install it in a directory using composer (See [Getting Started](https://github.com/tomzx/php-semver-checker#getting-started)).

At one point in the not so distant future, I will look into building/release .phar builds.

**Comment by xabbuh** [comment]
@tomzx You could attach the phar files to the matching tags on the [releases page](https://github.com/tomzx/php-semver-checker/releases).

**Comment by tomzx** [comment]
@xabbuh Sounds reasonable. I'll add it to the top of my task queue then.

**Comment by tomzx** [comment]
Alright, I've published a `.phar` for [v0.1.0](https://github.com/tomzx/php-semver-checker/releases/tag/v0.1.0) and [v0.2.0](https://github.com/tomzx/php-semver-checker/releases/tag/v0.2.0).

I'll submit `.phar` files on every new release.

Thanks for the help!

**Comment by temp** [comment]
@tomzx looks like there was no phar release since 0.6.3

**Comment by tomzx** [comment]
The latest phars can be found @ http://psvc.coreteks.org/.

**Comment by temp** [comment]
@tomzx thanks! but it would be nicer to have them on the release page. tools like phive would then be able to install the phar.

**Comment by tomzx** [comment]
I'll see what I can do about automating the release process on github.

Thanks for your suggestion @temp.

See #118 for the issue tracking this suggestion.
