### ISSUE TITLE
php fatal error when analyzing interface changes

### ISSUE THREAD

**Issue by vancoz** [tomzx/php-semver-checker#22]
PHP Fatal error:  Call to undefined method PhpParser\Node\Stmt\Interface_::getMethods() in /Users/igavryshko/projects/semVerChecker/src/PHPSemVerChecker/Analyzer/ClassMethodAnalyzer.php on line 45
PHP Stack trace:
PHP   1. {main}() /Users/igavryshko/projects/semVerChecker/bin/php-semver-checker:0
PHP   2. Symfony\Component\Console\Application->run() /Users/igavryshko/projects/semVerChecker/bin/php-semver-checker:26
PHP   3. Symfony\Component\Console\Application->doRun() /Users/igavryshko/projects/semVerChecker/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /Users/igavryshko/projects/semVerChecker/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /Users/igavryshko/projects/semVerChecker/vendor/symfony/console/Symfony/Component/Console/Application.php:878
PHP   6. PHPSemVerChecker\Console\Command\CompareCommand->execute() /Users/igavryshko/projects/semVerChecker/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   7. PHPSemVerChecker\Analyzer\Analyzer->analyze() /Users/igavryshko/projects/semVerChecker/src/PHPSemVerChecker/Console/Command/CompareCommand.php:59
PHP   8. PHPSemVerChecker\Analyzer\InterfaceAnalyzer->analyze() /Users/igavryshko/projects/semVerChecker/src/PHPSemVerChecker/Analyzer/Analyzer.php:29
PHP   9. PHPSemVerChecker\Analyzer\ClassMethodAnalyzer->analyze() /Users/igavryshko/projects/semVerChecker/src/PHPSemVerChecker/Analyzer/InterfaceAnalyzer.php:44

Fatal error: Call to undefined method PhpParser\Node\Stmt\Interface_::getMethods() in /Users/igavryshko/projects/semVerChecker/src/PHPSemVerChecker/Analyzer/ClassMethodAnalyzer.php on line 45

**Comment by tomzx** [comment]
Have you installed the new composer dependencies?

I had to add `getMethods` to nikic's php-parser for `Trait_` and `Interface_`. See the [PR](https://github.com/nikic/PHP-Parser/pull/166). Until it is part of the php-parser library, I've pointed to my fork.

**Comment by vancoz** [comment]
I have updated dependencies and it works now. Thank you.
