### ISSUE TITLE
What should php-semver-checker do in order to better integrate into current CI workflow?

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker#33]
The goal of this issue is to discuss how to make this tool into something that is useful to developers on a daily basis.

For the moment, it is pretty cumbersome to use the tool because you have to keep a version of your code you want to compare your current code against.

[**php-semver-checker-git**](https://github.com/tomzx/php-semver-checker-git) is a command utility that uses `php-semver-checker` in the context of a git repository. Using git it could be possible to ask only for the files that have changes between two commits, read and compare only those.

In the context of other vcs (specifically non-dvcs), we're back to square one (keeping a copy at a specific point in time). Thus at this point, the burden is on the user to determine how he'll retrieve the code of the release he wants to compare against.

I'd be happy to discuss the various use cases people may have for this tool.

**Comment by Anahkiasen** [comment]
Honestly I think it you manage to pull off an SVN adapter you're pretty much good to go: this is a PHP semver checker, almost all modern PHP packages that _worry_ about semver are on either Github or Bitbucket, so Git covers already an enormous chunk of Packagist. I'd wait until someone actually requests a different adapter to worry about it and focus on the actual checking part until then.
