### ISSUE TITLE
Excluding files/folders

### ISSUE THREAD

**Issue by Anahkiasen** [tomzx/php-semver-checker#34]
This may sound weird or go against the purpose, but is there any way to configure the checker for it to ignore specific files or folders?

Currently PSC will scan absolutely _all_ classes and consider any public method part of the public API. While this is _technically_ true there is a lot of classes in my code that are public while not being part of the "public" part of the package nor supposed to be used for public consumption. Classes like the ones that compile the PHAR and such, that aren't documented anywhere and are only there for internal use.

**Comment by Anahkiasen** [comment]
Or is this what #23 will bring?

**Comment by tomzx** [comment]
Exclusion at a file/folder level is what #23 should bring.
Exclusion of classes that do not use `@api` annotation in a package that uses it is what #8 should bring.

Hopefully these two cover most of the inclusion/exclusion people will need.

**Comment by tomzx** [comment]
Source filtering was added @ v0.6.3. Please try it out and let me know if you have any suggestions on how to improve it.
