### ISSUE TITLE
Use "src" folder as default 

### ISSUE THREAD

**Issue by Anahkiasen** [tomzx/php-semver-checker#35]
I think 90% of the packages out there have either a `src` or `lib` folder, any way to make this the default instead of having to do `php-semver-checker-git compare master develop src src` which looks rather weird?

**Comment by tomzx** [comment]
Yes. It is something I've already thought about. The `source-before` and `source-after` input arguments are most likely going to become input options and thus the regular command will be `php-semver-checker-git compare master develop`.

**Comment by tomzx** [comment]
For now, I prefer that `php-semver-checker` does not know about a "common" code structure.

I think it makes more sense to use a configuration file with default values, which allows something as simple as `php-semver-checker compare`.
