### ISSUE TITLE
Installing globally

### ISSUE THREAD

**Issue by tonglil** [tomzx/php-semver-checker#46]
Hi, when I try to install this globally with `composer global require tomzx/php-semver-checker --stability=dev`, composer says complains:

> The "--stability" option does not exist.

The docs say that the option only exists for "create-project" and "init".

How can I install the bleeding package globally?

**Comment by tomzx** [comment]
Hello @tonglil,

You are indeed correct. Composer does not have a `--stability` flag on the `composer global require`, which is my error.

As to how to install the bleeding package globally, it means that there's a couple of ways:
- Edit your global composer.json to set "minimum-stability": "dev" and try `composer global require tomzx/php-semver-checker`
- Use `create-project` in a specific folder, adding the `bin` folder to your $PATH/%PATH%

I will remove the `composer global require` from the README.md as it is incorrect.

Let me know if you need any more help.
