### ISSUE TITLE
Support CLI parameters in the configuration file

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker#67]
Currently, no value in the configuration is a value that can be given to a command of the console.

With this change, the configuration would add values such as source-before/source-after/include-before/include-after/exclude-before/exclude-after such that it is not necessary to specify them when calling commands.

However, if a configuration file exist with specific arguments, but different arguments are given when calling the CLI, those arguments should override those set in the configuration.

See #59.

**Comment by nochso** [comment]
See #72

**Comment by tomzx** [comment]
As per #74, this is done.
