### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nochso** [tomzx/php-semver-checker#72]
Hi. This is such a great tool and I'd like it to become easier to use.

I've started to refactor the CompareCommand so re-use should become much simpler. Meaning the `git` checker can be simplified afterwards.

Mixing file configuration and CLI arguments is what I'm also working on. I'll send a PR when it's ready.

**Comment by nochso** [comment]
I've started over as there were too many unrelated changes at once. I'll try refactoring a bit more atomically so merging doesn't become an issue.

**Comment by tomzx** [comment]
I'll consider that since #74 has been merged, this can be closed. If not, let me know and I'll reopen.
