### ISSUE TITLE
Comparing branches rather than filestore.

### ISSUE THREAD

**Issue by rquadling** [tomzx/php-semver-checker#89]
Hi.

Purely as a WIBNI (Wouldn't It Be Nice If...), rather than comparing 2 physical paths, would it possible/feasible to be able to compare branches?

I'm working on a feature branch and want to know what semver options I need to deal with compared to the current dev branch.

Any one got any ideas on this? Has it already been rejected?

**Comment by tomzx** [comment]
@rquadling Yes, it is possible to do this if you use git, see https://github.com/tomzx/php-semver-checker-git :smile:

However, do be careful as this needs to checkout code at a specified version in order to build a comparison report (it is not built off git change history, but from files changes).

**Comment by rquadling** [comment]
Thanks.
