### ISSUE TITLE
php-semver-checker is not installable anymore

### ISSUE THREAD

**Issue by mikeSimonson** [tomzx/php-semver-checker#90]
It require a branch of php-parser that doesn't exists anymore.

https://github.com/tomzx/php-semver-checker/blob/master/composer.json#L33

**Comment by mikeSimonson** [comment]
hum not sure anymore as I have been able to install it again.

**Comment by tomzx** [comment]
If you use `php-semver-checker` in a project with other dependencies (namely `php-parser`), it may causes some issues. However it should not cause a problem if used on its own.

Let me know if you still have this issue and I'll re-open this.

**Comment by mikeSimonson** [comment]
I only use https://packagist.org/packages/consolidation/cgr to install
tools globally now
